services:
  docs-ermis:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: thangbelo/docs-ermis:v1.0.2
    container_name: docs-ermis
    ports:
      - "127.0.0.1:3333:3334"
    restart: always